### ISSUE TITLE
Enhance TaskDate to handle not fully specified date and time.

### ISSUE THREAD

**Issue by KnewYouWereTrouble** [CS2103AUG2016-W13-C1/main#16]
For example
"d-MMM",
"d/MMM",
"d MMM",
"MMMM d",
"MMM d",
"d/M", 
"d-M"

**Comment by KnewYouWereTrouble** [comment]
also for example
"tomorrow",
"yesterday",
"today",
"next monday",
"last thursday"

**Comment by Goutami2122** [comment]
i think in data base you have create a table for date,time 
create table tablename(date1 DATE,time1 TIME, timestamp1 TIMESTAMP, timestamp2 TIMESTAMP);
insert into  tablename(date1,time1) VALUES ('2006-01-03','15:26:02');

afterthat you have to write code in for date printing.

**Comment by KnewYouWereTrouble** [comment]
#54
